# -*- coding: utf-8 -*-
"""18th dec

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_38aMKs6xJFtYTTrZ3xboSUinGZbdc67
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
sns.get_dataset_names()

df=sns.load_dataset("tips")
df

df.shape

df.columns

df.info()

df.describe()

#insight
describe given numerical np.columns
dataset have 244 records
no missing values in total_bill,tip,size

--total_bill--
avg

df.describe(include='category')

from typing import dataclass_transform
from pandas._config.config import Mode
from numpy._core import records
#null value treatments and imputation
A. Fill the missing records
     1. Mean Median Mode
     2. domain
B. Remove missing dataclass_transform
     1. Remove the rows in which missing position
        dropna data loss less than 20
     2. Remove the column in which missing positions

(df.isna().sum()/df.shape[0])*100

df=sns.load_dataset("titanic")
df

df.shape

df.isna().sum() #find no. of missing values

(df.isna().sum()/df.shape[0])*100 #percentage of missing values

df.dropna() #it will not delete data permenantly remove records temporarily

df.dropna().shape

df.shape

df.dropna().shape[0]

df.info()

((891-182)/891)*100

((df.shape[0]-df.dropna().shape[0])/df.shape[0])*100 #loss percentage

"""deck perct of missing records is more than 20 or it is 77 percent ,we can remove deck

age - np.median
embark_town mode
embarked median/

# numerical values
survived
pclass
sibsp
parch
age
fare
"""

plt.figure(figsize=(3,2))
sns.histplot(x=df['survived'])
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['age'])
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['pclass'])
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['parch'])
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['sibsp'])
plt.show()

plt.figure(figsize=(10,2))
sns.histplot(x=df['fare'])
plt.show()

"""#categorical
sex
embarked
class
embark_town
who
deck
adult_male
alive
alone
"""

plt.figure(figsize=(3,2))
sns.countplot(x=df['sex'])
plt.show()

plt.figure(figsize=(3,2))
sns.countplot(x=df['embarked'])
plt.show()

plt.figure(figsize=(3,2))
sns.countplot(x=df['class'])
plt.show()

plt.figure(figsize=(3,2))
sns.countplot(x=df['embark_town'])
plt.show()

plt.figure(figsize=(3,2))
sns.countplot(x=df['who'])
plt.show()

plt.figure(figsize=(3,2))
sns.countplot(x=df['deck'])
plt.show()

plt.figure(figsize=(3,2))
sns.countplot(x=df['adult_male'])
plt.show()

plt.figure(figsize=(3,2))
sns.countplot(x=df['alive'])
plt.show()

plt.figure(figsize=(3,2))
sns.countplot(x=df['alone'])
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['survived'],hue=df['sex'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['age'],hue=df['sex'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['pclass'],hue=df['sex'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['parch'],hue=df['sex'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['sibsp'],hue=df['sex'],kde=True)
plt.show()

plt.figure(figsize=(8,2))
sns.histplot(x=df['fare'],hue=df['sex'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['survived'],hue=df['embarked'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['pclass'],hue=df['embarked'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['sibsp'],hue=df['embarked'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['parch'],hue=df['embarked'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['age'],hue=df['embarked'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['fare'],hue=df['embarked'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['survived'],hue=df['class'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['pclass'],hue=df['class'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['sibsp'],hue=df['class'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['parch'],hue=df['class'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['age'],hue=df['class'],kde=True)
plt.show()

plt.figure(figsize=(8,2))
sns.histplot(x=df['fare'],hue=df['class'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['survived'],hue=df['who'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['pclass'],hue=df['who'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['sibsp'],hue=df['who'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['parch'],hue=df['who'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['age'],hue=df['who'],kde=True)
plt.show()
plt.figure(figsize=(8,2))
sns.histplot(x=df['fare'],hue=df['who'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['survived'],hue=df['embark_town'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['pclass'],hue=df['embark_town'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['sibsp'],hue=df['embark_town'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['parch'],hue=df['embark_town'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['age'],hue=df['embark_town'],kde=True)
plt.show()
plt.figure(figsize=(8,2))
sns.histplot(x=df['fare'],hue=df['embark_town'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['survived'],hue=df['adult_male'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['pclass'],hue=df['adult_male'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['sibsp'],hue=df['adult_male'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['parch'],hue=df['adult_male'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['age'],hue=df['adult_male'],kde=True)
plt.show()
plt.figure(figsize=(8,2))
sns.histplot(x=df['fare'],hue=df['adult_male'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['survived'],hue=df['alive'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['pclass'],hue=df['alive'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['sibsp'],hue=df['alive'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['parch'],hue=df['alive'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['age'],hue=df['alive'],kde=True)
plt.show()
plt.figure(figsize=(8,2))
sns.histplot(x=df['fare'],hue=df['alive'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.histplot(x=df['survived'],hue=df['alone'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['pclass'],hue=df['alone'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['sibsp'],hue=df['alone'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['parch'],hue=df['alone'],kde=True)
plt.show()
plt.figure(figsize=(3,2))
sns.histplot(x=df['age'],hue=df['alone'],kde=True)
plt.show()
plt.figure(figsize=(8,2))
sns.histplot(x=df['fare'],hue=df['alone'],kde=True)
plt.show()

plt.figure(figsize=(3,2))
sns.countplot(x=df['sex'],hue=df['embarked'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['sex'],hue=df['class'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['sex'],hue=df['who'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['sex'],hue=df['embark_town'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['sex'],hue=df['adult_male'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['sex'],hue=df['alive'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['sex'],hue=df['alone'])
plt.show()

plt.figure(figsize=(3,2))
sns.countplot(x=df['embarked'],hue=df['class'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['embarked'],hue=df['who'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['embarked'],hue=df['embark_town'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['embarked'],hue=df['adult_male'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['embarked'],hue=df['alive'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['embarked'],hue=df['alone'])
plt.show()

plt.figure(figsize=(3,2))
sns.countplot(x=df['class'],hue=df['who'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['class'],hue=df['embark_town'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['class'],hue=df['adult_male'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['class'],hue=df['alive'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['class'],hue=df['alone'])
plt.show()

plt.figure(figsize=(3,2))
sns.countplot(x=df['who'],hue=df['embark_town'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['who'],hue=df['adult_male'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['who'],hue=df['alive'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['who'],hue=df['alone'])
plt.show()

plt.figure(figsize=(3,2))
sns.countplot(x=df['embark_town'],hue=df['adult_male'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['embark_town'],hue=df['alive'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['embark_town'],hue=df['alone'])
plt.show()

plt.figure(figsize=(3,2))
sns.countplot(x=df['adult_male'],hue=df['alive'])
plt.show()
plt.figure(figsize=(3,2))
sns.countplot(x=df['adult_male'],hue=df['alone'])
plt.show()

plt.figure(figsize=(3,2))
sns.countplot(x=df['alive'],hue=df['alone'])
plt.show()